[package]
name = "part3"
version = "0.1.0"
edition = "2024"

[dependencies]
linfa = { git = "https://github.com/rust-ml/linfa" }
linfa-linear = { git = "https://github.com/rust-ml/linfa" }
ndarray = { version = "^0.15.6" }